# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb_forum', '0002_auto_20161121_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_club_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_club',
            field=models.BooleanField(default=False),
        ),
    ]
